// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication3.Data;

#nullable disable

namespace MyApplication3.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250617183323_AddedSeedingDataDairyEntry")]
    partial class AddedSeedingDataDairyEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApplication3.Models.DairyEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DairyEntries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Content = "Went with my friend",
                            Created = new DateTime(2025, 6, 17, 11, 33, 18, 928, DateTimeKind.Local).AddTicks(3912),
                            Title = "Outing"
                        },
                        new
                        {
                            id = 2,
                            Content = "Went with my friend",
                            Created = new DateTime(2025, 6, 17, 11, 33, 18, 928, DateTimeKind.Local).AddTicks(4423),
                            Title = "Shopping"
                        },
                        new
                        {
                            id = 3,
                            Content = "To  Home Town",
                            Created = new DateTime(2025, 6, 17, 11, 33, 18, 928, DateTimeKind.Local).AddTicks(4427),
                            Title = "Travelling"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
